#[metasploitable]
#msf1 ansible_host=10.0.30.47 ansible_user=msfadmin ansible_password=msfadmin ansible_become=false ansible_python_interpreter=/bin/false

#[metasploitable:vars]
#ansible_ssh_common_args='-o HostkeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa'

#[kali]
#kali1 ansible_host=10.0.30.65 ansible_user=bob ansible_ssh_private_key_file=/home/ansible/.ssh/id_ed25519
[kali-test]
#kali1 ansible_host=10.0.30.50 ansible_user=kali ansible_ssh_private_key_file=/home/ansible/.ssh/id_ed25519
kali1 ansible_host=10.0.30.50 ansible_user=kali ansible_ssh_private_key_file=/home/ansible/.ssh/id_rsa

[ctfd]
ctfd1 ansible_host=10.0.30.66 ansible_user=ctfd ansible_ssh_private_key_file=/home/ansible/.ssh/id_rsa

#[wazuh]
#wazuh ansible_host=10.0.30.90 ansible_user=wazuh

#[agents]
#agent1 ansible_host=10.0.30.16 wazuh_agent_name=AGENT-01 ansible_user=agent ansible_ssh_private_key_file=/home/ansible/.ssh/id_rsa

[fauxpositif]
fp1 ansible_host=10.0.30.24  ansible_user=fp ansible_ssh_private_key_file=/home/ansible/.ssh/id_rsa
[wazuh-meduim]
wazuh ansible_host=10.0.30.65 ansible_user=wazuh
[agent-meduim]
agent1 ansible_host=10.0.30.25 ansible_user=agent  ansible_ssh_private_key_file=/home/ansible/.ssh/id_rsa
