- hosts: agent-meduim
  become: yes
  tasks:
    - name: Ensure testuser exists
      ansible.builtin.user:
        name: testuser
        password: "{{ '123456' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

- hosts: kali-test
  become: yes
  tasks:
    - name: Copy brute force attack script
      ansible.builtin.copy:
        src: files/autoattack2.sh
        dest: /usr/local/bin/autoattack2.sh
        mode: '0755'

    - name: Deploy brute force service
      ansible.builtin.copy:
        src: files/autoattack2.service
        dest: /etc/systemd/system/autoattack2.service
        mode: '0644'

    - name: Deploy brute force timer
      ansible.builtin.copy:
        src: files/autoattack2.timer
        dest: /etc/systemd/system/autoattack2.timer
        mode: '0644'

    - name: Reload systemd (Kali)
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start brute force timer
      ansible.builtin.systemd:
        name: autoattack2.timer
        enabled: yes
        state: started


- hosts: wazuh-meduim
  become: yes
  tasks:
    - name: Ensure sshpass is installed
      ansible.builtin.package:
        name: sshpass
        state: present

    - name: Copy legitimate SSH script
      ansible.builtin.copy:
        src: files/legit_ssh.sh
        dest: /usr/local/bin/legit_ssh.sh
        mode: '0755'

    - name: Deploy legitimate SSH service
      ansible.builtin.copy:
        src: files/legit_ssh.service
        dest: /etc/systemd/system/legit_ssh.service
        mode: '0644'

    - name: Deploy legitimate SSH timer
      ansible.builtin.copy:
        src: files/legit_ssh.timer
        dest: /etc/systemd/system/legit_ssh.timer
        mode: '0644'

    - name: Reload systemd (Ubuntu legit)
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start legitimate SSH timer
      ansible.builtin.systemd:
        name: legit_ssh.timer
        enabled: yes
        state: started

    - name: Block Wazuh manager port (simulate connectivity issue)
      ansible.builtin.command: >
        iptables -A INPUT -p tcp --dport 1514 -j DROP

   

- hosts: fauxpositif
  become: yes
  tasks:
    - name: Ensure sshpass is installed
      ansible.builtin.package:
        name: sshpass
        state: present

    - name: Copy false positive SSH script
      ansible.builtin.copy:
        src: files/fauxpositif.sh
        dest: /usr/local/bin/fauxpositif.sh
        mode: '0755'

    - name: Deploy false positive service
      ansible.builtin.copy:
        src: files/fauxpositif.service
        dest: /etc/systemd/system/fauxpositif.service
        mode: '0644'

    - name: Deploy false positive timer
      ansible.builtin.copy:
        src: files/fauxpositif.timer
        dest: /etc/systemd/system/fauxpositif.timer
        mode: '0644'

    - name: Reload systemd (Ubuntu fauxpositif)
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start false positive timer
      ansible.builtin.systemd:
        name: fauxpositif.timer
        enabled: yes
        state: started

